import { ethers } from 'ethers';

// ALCHEMY
enum END_POINT {
    ETH_MAINNET = 'https://eth-mainnet.g.alchemy.com/v2',
    ETH_SEPOLIA = 'https://eth-sepolia.g.alchemy.com/v2',
    ARBITRUM_ONE = 'https://arb-mainnet.g.alchemy.com/v2',
}

const createJsonRpcProviderAndLogInfo = async (url: string) => {
    const provider = new ethers.JsonRpcProvider(url);
    const network = await provider.getNetwork();
    console.log('Network:', network.name, '\tID:', network.chainId);
    return provider;
};

const initialize = async (endpoint: END_POINT) => {
    // generated by: openssl rand -hex 32
    const PRIVATE_KEY1 = process.env.ETH_KEY1 as string;
    const PRIVATE_KEY2 = process.env.ETH_KEY2 as string;
    const API_KEY = process.env.ALCHEMY_API_KEY as string;

    return {
        wallet1: new ethers.Wallet(PRIVATE_KEY1),
        wallet2: new ethers.Wallet(PRIVATE_KEY2),
        provider: await createJsonRpcProviderAndLogInfo(
            `${endpoint}/${API_KEY}`,
        ),
    };
};

const queryBalance = async (provider: ethers.Provider, address: string) => {
    const balance = await provider.getBalance(address);
    console.log(
        `ETH Balance of ${address} --> ${ethers.formatEther(balance)} ETH`,
    );
    return balance;
};

const checkAccountInfo = async (provider: ethers.Provider, address: string) => {
    queryBalance(provider, address);

    const txcount = await provider.getTransactionCount(address);
    console.log('nonce of ${address} -->', txcount);

    const feeData = await provider.getFeeData();
    console.log('fee data:', feeData);
};

const playWithProvider = async (provider: ethers.Provider) => {
    const blockNumber = await provider.getBlockNumber();
    console.log('current block number: ', blockNumber);
};

const readContractInfo = async (provider: ethers.Provider) => {
    const ERC20_ABI = [
        'function name() view returns (string)',
        'function symbol() view returns (string)',
        'function totalSupply() view returns (uint256)',
        'function balanceOf(address) view returns (uint)',
    ];
    const DAI_ADDRESS = '0x6B175474E89094C44Da98b954EedeAC495271d0F'; // DAI Contract
    const DAI_CONTRACT = new ethers.Contract(DAI_ADDRESS, ERC20_ABI, provider);

    const name = await DAI_CONTRACT.name();
    const symbol = await DAI_CONTRACT.symbol();
    const totalSupply = await DAI_CONTRACT.totalSupply();

    console.log(`\nReading from ${DAI_ADDRESS}\n`);
    console.log(`Name: ${name}`);
    console.log(`Symbol: ${symbol}`);
    console.log(`Total Supply: ${ethers.formatEther(totalSupply)}`);

    const balanceAddress = 'vitalik.eth';
    const balance = await DAI_CONTRACT.balanceOf(balanceAddress);
    console.log(`Vitalik's Balance: ${ethers.formatEther(balance)}\n`);
};

const sendEth = async (
    provider: ethers.Provider,
    wallet1: ethers.Wallet,
    wallet2: ethers.Wallet,
    amountInWei: bigint,
) => {
    const feeData = await provider.getFeeData();
    console.log('fee data:', feeData);

    const address1 = wallet1.address;
    const address2 = wallet2.address;
    console.log('address:', address1, address2);

    console.log('before...');

    const balance = await queryBalance(provider, address1);
    await queryBalance(provider, address2);
    console.log(balance);

    const tx = await wallet1.sendTransaction({
        to: address2,
        value: amountInWei,
    });
    console.log('tx commited. waiting for confirmation...');
    await tx.wait();
    console.log(tx);

    console.log('after...');

    queryBalance(provider, address1);
    queryBalance(provider, address2);
};

const play = async () => {
    const { provider, wallet1, wallet2 } = await initialize(
        END_POINT.ETH_MAINNET,
    );
    await playWithProvider(provider);
    await readContractInfo(provider);
    await checkAccountInfo(provider, wallet1.address);
    await checkAccountInfo(provider, wallet2.address);
};

play();
